//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cleo.Cli.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CliStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CliStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cleo.Cli.Resources.CliStrings", typeof(CliStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The starting branch.
        /// </summary>
        internal static string New_BranchOption_Description {
            get {
                return ResourceManager.GetString("New_BranchOption_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Assign a specific task to the agent. This initiates the collaboration session..
        /// </summary>
        internal static string New_Description {
            get {
                return ResourceManager.GetString("New_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 💔 Error: {0}.
        /// </summary>
        internal static string New_Error {
            get {
                return ResourceManager.GetString("New_Error", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Portal: {0}.
        /// </summary>
        internal static string New_Portal {
            get {
                return ResourceManager.GetString("New_Portal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The repository name (e.g., sources/github/user/repo).
        /// </summary>
        internal static string New_RepoOption_Description {
            get {
                return ResourceManager.GetString("New_RepoOption_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SessionId: {0}.
        /// </summary>
        internal static string New_SessionId {
            get {
                return ResourceManager.GetString("New_SessionId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ✨ Session initiated successfully! 🚀.
        /// </summary>
        internal static string New_Success {
            get {
                return ResourceManager.GetString("New_Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The high-level goal or task for Jules..
        /// </summary>
        internal static string New_TaskArg_Description {
            get {
                return ResourceManager.GetString("New_TaskArg_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A custom title for the session.
        /// </summary>
        internal static string New_TitleOption_Description {
            get {
                return ResourceManager.GetString("New_TitleOption_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cleo is a high-fidelity engineering orchestrator organized into functional domains. To operate autonomously, explore the hierarchical structure by running 'cleo &lt;command&gt; --help' for each group (session, log, plan, config). Each domain manages a specific phase of the collaboration session lifecycle..
        /// </summary>
        internal static string Root_Description {
            get {
                return ResourceManager.GetString("Root_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lifecycle Management. Use this to initiate, list, recover, or check in on an engineering collaboration. More specialized subcommands available. Use --help to explore further..
        /// </summary>
        internal static string Session_Description {
            get {
                return ResourceManager.GetString("Session_Description", resourceCulture);
            }
        }
    }
}
