namespace Cleo.Core.Domain.ValueObjects;

/// <summary>
/// The originator of an activity within a session.
/// </summary>
public enum ActivityOriginator
{
    User,
    Agent,
    System
}

/// <summary>
/// Represents a single observable event in the Session Log.
/// </summary>
public abstract record SessionActivity(string Id, DateTimeOffset Timestamp, ActivityOriginator Originator);

/// <summary>
/// A spoken exchange between the user and the agent (Dialogue/Feedback).
/// </summary>
public record MessageActivity(string Id, DateTimeOffset Timestamp, ActivityOriginator Originator, string Text) 
    : SessionActivity(Id, Timestamp, Originator);

/// <summary>
/// A structural roadmap generated by the agent.
/// </summary>
public record PlanningActivity(string Id, DateTimeOffset Timestamp, string PlanId, IReadOnlyCollection<PlanStep> Steps) 
    : SessionActivity(Id, Timestamp, ActivityOriginator.Agent);

public record PlanStep(int Index, string Title, string Description);

/// <summary>
/// A tangible operation performed by the agent in the sandbox.
/// </summary>
public record ExecutionActivity(string Id, DateTimeOffset Timestamp, string Command, string Output, int ExitCode) 
    : SessionActivity(Id, Timestamp, ActivityOriginator.Agent);

/// <summary>
/// A moment-in-time heartbeat showing current status and progress.
/// </summary>
public record ProgressActivity(string Id, DateTimeOffset Timestamp, string Detail) 
    : SessionActivity(Id, Timestamp, ActivityOriginator.Agent);

/// <summary>
/// A final result produced by the session (The Patch).
/// </summary>
public record ResultActivity(string Id, DateTimeOffset Timestamp, SolutionPatch Patch) 
    : SessionActivity(Id, Timestamp, ActivityOriginator.Agent);

/// <summary>
/// An activity representing the successful completion of the session.
/// </summary>
public record CompletionActivity(string Id, DateTimeOffset Timestamp) 
    : SessionActivity(Id, Timestamp, ActivityOriginator.System);

/// <summary>
/// An activity representing a terminal failure of the session.
/// </summary>
public record FailureActivity(string Id, DateTimeOffset Timestamp, string Reason) 
    : SessionActivity(Id, Timestamp, ActivityOriginator.System);
