namespace Cleo.Core.Domain.ValueObjects;

/// <summary>
/// The originator of an activity within a session.
/// </summary>
public enum ActivityOriginator
{
    User,
    Agent,
    System
}

/// <summary>
/// A tangible unit of data produced during a session activity.
/// </summary>
public abstract record Artifact
{
    public abstract string GetSummary();
}

/// <summary>
/// Represents a single observable event in the Session Log.
/// Acts as a container for hierarchical Artifacts (Evidence).
/// </summary>
public abstract record SessionActivity(
    string Id, 
    string RemoteId,
    DateTimeOffset Timestamp, 
    ActivityOriginator Originator,
    IReadOnlyCollection<Artifact> Evidence,
    string? ExecutiveSummary = null)
{
    /// <summary>
    /// Returns a human-friendly summary of the activity's primary content.
    /// </summary>
    public abstract string GetContentSummary();

    /// <summary>
    /// Returns technical or metadata details about the activity.
    /// </summary>
    public virtual string GetMetaDetail() => $"Originator: {Originator} | Evidence: {Evidence.Count}";

    /// <summary>
    /// Indicates whether this activity represents a major state transition or communication event.
    /// </summary>
    public virtual bool IsSignificant => true;

    /// <summary>
    /// Returns the internal reasoning or thoughts associated with this activity, if any.
    /// </summary>
    public virtual IEnumerable<string> GetThoughts() => Enumerable.Empty<string>();

    /// <summary>
    /// Returns the visual symbol for this activity.
    /// </summary>
    public virtual string GetSymbol() => "🔹";

    /// <summary>
    /// The authoritative headline for this activity.
    /// Prioritizes the Executive Summary if available, falling back to the Content Summary.
    /// </summary>
    public virtual string Headline => !string.IsNullOrWhiteSpace(ExecutiveSummary) ? ExecutiveSummary : GetContentSummary();
}

/// <summary>
/// A spoken exchange between the user and the agent (Dialogue/Feedback).
/// </summary>
public record MessageActivity(
    string Id, 
    string RemoteId,
    DateTimeOffset Timestamp, 
    ActivityOriginator Originator, 
    string Text,
    IReadOnlyCollection<Artifact>? Evidence = null,
    string? ExecutiveSummary = null)
    : SessionActivity(Id, RemoteId, Timestamp, Originator, Evidence ?? Array.Empty<Artifact>(), ExecutiveSummary)
{
    public override string GetContentSummary() => Text;

    public override string GetSymbol() => Originator switch
    {
        ActivityOriginator.User => "👤",
        ActivityOriginator.Agent => "👸",
        _ => "💬"
    };
}

/// <summary>
/// The initial activity marking the assignment of a task to the session.
/// Enforces the 'Zero-Hollow' invariant.
/// </summary>
public record SessionAssignedActivity(
    string Id,
    string RemoteId,
    DateTimeOffset Timestamp,
    ActivityOriginator Originator,
    TaskDescription Task,
    IReadOnlyCollection<Artifact>? Evidence = null,
    string? ExecutiveSummary = null)
    : SessionActivity(Id, RemoteId, Timestamp, Originator, Evidence ?? Array.Empty<Artifact>(), ExecutiveSummary)
{
    public override string GetContentSummary() => $"Session Assigned: {Task}";
    public override string GetSymbol() => "🚀";
}

/// <summary>
/// A structural roadmap generated by the agent.
/// </summary>
public record PlanningActivity(
    string Id, 
    string RemoteId,
    DateTimeOffset Timestamp, 
    ActivityOriginator Originator,
    string PlanId, 
    IReadOnlyCollection<PlanStep> Steps,
    IReadOnlyCollection<Artifact>? Evidence = null,
    string? ExecutiveSummary = null)
    : SessionActivity(Id, RemoteId, Timestamp, Originator, Evidence ?? Array.Empty<Artifact>(), ExecutiveSummary)
{
    public override string GetContentSummary() => $"Plan Generated: {PlanId} ({Steps.Count} steps)";
    public override string GetMetaDetail() => $"{base.GetMetaDetail()} | Steps: {Steps.Count}";
    public override string GetSymbol() => "🗺️";
}

public record PlanStep(string Id, int Index, string Title, string Description);

/// <summary>
/// A formal approval of a proposed plan.
/// </summary>
public record ApprovalActivity(
    string Id, 
    string RemoteId,
    DateTimeOffset Timestamp, 
    ActivityOriginator Originator,
    string PlanId,
    IReadOnlyCollection<Artifact>? Evidence = null,
    string? ExecutiveSummary = null)
    : SessionActivity(Id, RemoteId, Timestamp, Originator, Evidence ?? Array.Empty<Artifact>(), ExecutiveSummary)
{
    public override string GetContentSummary() => $"Plan Approved: {PlanId}";
    public override string GetSymbol() => "✅";
}

/// <summary>
/// A moment-in-time heartbeat showing current status, progress, and internal reasoning.
/// </summary>
public record ProgressActivity(
    string Id, 
    string RemoteId,
    DateTimeOffset Timestamp, 
    ActivityOriginator Originator,
    string Intent,
    string? Reasoning = null,
    IReadOnlyCollection<Artifact>? Evidence = null,
    string? ExecutiveSummary = null)
    : SessionActivity(Id, RemoteId, Timestamp, Originator, Evidence ?? Array.Empty<Artifact>(), ExecutiveSummary)
{
    /// <summary>
    /// The high-level intent or state (e.g., "Working...", "Code Review").
    /// </summary>
    public string Intent { get; init; } = Intent;

    /// <summary>
    /// The agent's internal monologue or reasoning signal.
    /// </summary>
    public string? Reasoning { get; init; } = Reasoning;

    public override string GetContentSummary() => Intent;

    /// <summary>
    /// Determines if the activity is significant based on the Narrative Intelligence Policy.
    /// Significant if it contains a Thought (Reasoning Signal) or Evidence (Outcome Signal).
    /// </summary>
    public override bool IsSignificant
    {
        get
        {
            // Reasoning Signal: Has a non-empty thought/description
            if (!string.IsNullOrWhiteSpace(Reasoning)) return true;

            // Outcome Signal: Has tangible artifacts
            if (Evidence.Count > 0) return true;

            // Trace Signal: Pure system/status heartbeat
            return false;
        }
    }

    public override IEnumerable<string> GetThoughts()
    {
        if (string.IsNullOrWhiteSpace(Reasoning)) return Enumerable.Empty<string>();
        return Reasoning.Split('\n', StringSplitOptions.RemoveEmptyEntries);
    }

    public override string GetSymbol() => !string.IsNullOrWhiteSpace(Reasoning) ? "🧠" : "📡";
}

/// <summary>
/// An activity representing the successful completion of the session.
/// </summary>
public record CompletionActivity(
    string Id, 
    string RemoteId,
    DateTimeOffset Timestamp,
    ActivityOriginator Originator,
    IReadOnlyCollection<Artifact>? Evidence = null,
    string? ExecutiveSummary = null)
    : SessionActivity(Id, RemoteId, Timestamp, Originator, Evidence ?? Array.Empty<Artifact>(), ExecutiveSummary)
{
    public override string GetContentSummary() => "Session Completed Successfully";
    public override string GetSymbol() => "🏁";
}

/// <summary>
/// An activity representing a terminal failure of the session.
/// </summary>
public record FailureActivity(
    string Id, 
    string RemoteId,
    DateTimeOffset Timestamp, 
    ActivityOriginator Originator,
    string Reason,
    IReadOnlyCollection<Artifact>? Evidence = null,
    string? ExecutiveSummary = null)
    : SessionActivity(Id, RemoteId, Timestamp, Originator, Evidence ?? Array.Empty<Artifact>(), ExecutiveSummary)
{
    public override string GetContentSummary() => $"FAILURE: {Reason}";
    public override string GetSymbol() => "💥";

    public override string Headline => Reason;
}
