namespace Cleo.Core.Domain.ValueObjects;

/// <summary>
/// The originator of an activity within a session.
/// </summary>
public enum ActivityOriginator
{
    User,
    Agent,
    System
}

/// <summary>
/// A tangible unit of data produced during a session activity.
/// </summary>
public abstract record Artifact
{
    public abstract string GetSummary();
}

/// <summary>
/// Represents a single observable event in the Session Log.
/// Acts as a container for hierarchical Artifacts (Evidence).
/// </summary>
public abstract record SessionActivity(
    string Id, 
    string RemoteId,
    DateTimeOffset Timestamp, 
    ActivityOriginator Originator,
    IReadOnlyCollection<Artifact> Evidence)
{
    /// <summary>
    /// Returns a human-friendly summary of the activity's primary content.
    /// </summary>
    public abstract string GetContentSummary();

    /// <summary>
    /// Returns technical or metadata details about the activity.
    /// </summary>
    public virtual string GetMetaDetail() => $"Originator: {Originator} | Evidence: {Evidence.Count}";

    /// <summary>
    /// Indicates whether this activity represents a major state transition or communication event.
    /// </summary>
    public virtual bool IsSignificant => true;
}

/// <summary>
/// A spoken exchange between the user and the agent (Dialogue/Feedback).
/// </summary>
public record MessageActivity(
    string Id, 
    string RemoteId,
    DateTimeOffset Timestamp, 
    ActivityOriginator Originator, 
    string Text,
    IReadOnlyCollection<Artifact>? Evidence = null) 
    : SessionActivity(Id, RemoteId, Timestamp, Originator, Evidence ?? Array.Empty<Artifact>())
{
    public override string GetContentSummary() => Text;
}

/// <summary>
/// A structural roadmap generated by the agent.
/// </summary>
public record PlanningActivity(
    string Id, 
    string RemoteId,
    DateTimeOffset Timestamp, 
    ActivityOriginator Originator,
    string PlanId, 
    IReadOnlyCollection<PlanStep> Steps,
    IReadOnlyCollection<Artifact>? Evidence = null) 
    : SessionActivity(Id, RemoteId, Timestamp, Originator, Evidence ?? Array.Empty<Artifact>())
{
    public override string GetContentSummary() => $"Plan Generated: {PlanId} ({Steps.Count} steps)";
    public override string GetMetaDetail() => $"{base.GetMetaDetail()} | Steps: {Steps.Count}";
}

public record PlanStep(string Id, int Index, string Title, string Description);

/// <summary>
/// A formal approval of a proposed plan.
/// </summary>
public record ApprovalActivity(
    string Id, 
    string RemoteId,
    DateTimeOffset Timestamp, 
    ActivityOriginator Originator,
    string PlanId,
    IReadOnlyCollection<Artifact>? Evidence = null)
    : SessionActivity(Id, RemoteId, Timestamp, Originator, Evidence ?? Array.Empty<Artifact>())
{
    public override string GetContentSummary() => $"Plan Approved: {PlanId}";
}

/// <summary>
/// A moment-in-time heartbeat showing current status, progress, and internal reasoning.
/// </summary>
public record ProgressActivity(
    string Id, 
    string RemoteId,
    DateTimeOffset Timestamp, 
    ActivityOriginator Originator,
    string Title,
    string? Description = null,
    IReadOnlyCollection<Artifact>? Evidence = null) 
    : SessionActivity(Id, RemoteId, Timestamp, Originator, Evidence ?? Array.Empty<Artifact>())
{
    /// <summary>
    /// The high-level intent or state (e.g., "Working...", "Code Review").
    /// Maps to the API 'title' field.
    /// </summary>
    public string Intent => Title;

    /// <summary>
    /// The agent's internal monologue or reasoning signal.
    /// Maps to the API 'description' field.
    /// </summary>
    public string? Thought => Description;

    private const string Indent = "          "; // Indent to match "- [HH:mm] "

    public override string GetContentSummary()
    {
        var sb = new System.Text.StringBuilder();
        sb.Append(Intent);

        if (!string.IsNullOrWhiteSpace(Thought))
        {
            sb.AppendLine();
            sb.Append(Indent);
            sb.Append("💭 ");
            sb.Append(Thought.Replace("\n", $"\n{Indent}   ", StringComparison.Ordinal));
        }

        if (Evidence.Count > 0)
        {
            sb.AppendLine();
            sb.Append(Indent);
            sb.Append("📦 ");
            sb.Append(string.Join($"\n{Indent}📦 ", Evidence.Select(e => e.GetSummary())));
        }

        return sb.ToString();
    }

    /// <summary>
    /// Determines if the activity is significant based on the Narrative Intelligence Policy.
    /// Significant if it contains a Thought (Reasoning Signal) or Evidence (Outcome Signal).
    /// </summary>
    public override bool IsSignificant
    {
        get
        {
            // Reasoning Signal: Has a non-empty thought/description
            if (!string.IsNullOrWhiteSpace(Thought)) return true;

            // Outcome Signal: Has tangible artifacts
            if (Evidence.Count > 0) return true;

            // Trace Signal: Pure system/status heartbeat
            return false;
        }
    }
}

/// <summary>
/// An activity representing the successful completion of the session.
/// </summary>
public record CompletionActivity(
    string Id, 
    string RemoteId,
    DateTimeOffset Timestamp,
    ActivityOriginator Originator,
    IReadOnlyCollection<Artifact>? Evidence = null) 
    : SessionActivity(Id, RemoteId, Timestamp, Originator, Evidence ?? Array.Empty<Artifact>())
{
    public override string GetContentSummary()
    {
        var baseMsg = "Session Completed Successfully";
        if (Evidence.Count > 0)
        {
            return $"{baseMsg} | {string.Join(" | ", Evidence.Select(e => e.GetSummary()))}";
        }
        return baseMsg;
    }
}

/// <summary>
/// An activity representing a terminal failure of the session.
/// </summary>
public record FailureActivity(
    string Id, 
    string RemoteId,
    DateTimeOffset Timestamp, 
    ActivityOriginator Originator,
    string Reason,
    IReadOnlyCollection<Artifact>? Evidence = null) 
    : SessionActivity(Id, RemoteId, Timestamp, Originator, Evidence ?? Array.Empty<Artifact>())
{
    public override string GetContentSummary() => $"FAILURE: {Reason}";
}
